FROM alpine:3.21.0

WORKDIR /fusion
COPY fusion ./fusion
RUN chmod 755 ./fusion

EXPOSE 8080
VOLUME ["/data"]
ENV DB="/data/fusion.db"
HEALTHCHECK --interval=10s --timeout=3s --start-period=2s --retries=3 \
  CMD wget -q -O /dev/null http://127.0.0.1:8080/api/oidc/enabled || exit 1

CMD ["./fusion"]
